{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float borderWidth;\n\nvec4 fragColor;\n\nvec2 iResolution;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    iResolution = uSize;\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 remap = iResolution - fragCoord;\n    float val = 1.0 - (length(max(remap - (iResolution - vec2(borderWidth)), vec2(0.0))) / borderWidth);\n    val = smoothstep(0.0, 1.0, val);\n    fragColor = vec4(val, val, val, val) * 0.89999997615814208984375;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "uSize",
      "rows": 2,
      "type": 10
    },
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 1,
      "name": "borderWidth",
      "rows": 1,
      "type": 10
    }
  ]
}