name: Build

on:
  push:
    branches:
      - main

jobs:
  tag:
    permissions: write-all
    outputs:
      version: ${{ needs.tag.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tag if new version
        id: tag-release
        uses: jacopocarlini/action-autotag@3.0.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
      - name: Get version
        id: get-version
        run: |
          version=$(echo ${{  steps.tag-release.outputs.tagname }}" | cut -d 2-)
          echo "::set-output name=version::$version"
  build-web:
    needs: [tag]
    if: needs.tag.outputs.version != ''
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build
        run: flutter build web --web-renderer canvaskit --release --csp --base-href "/pix_reader/"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
  build-mac:
    needs: [tag]
    if: needs.tag.outputs.version != ''
    permissions: write-all
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build
        run: flutter config --enable-macos-desktop && flutter build --release
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install DMG creator
        run: npm install --global create-dmg
      - name: Create DMG
        run: create-dmg 'build/macos/Build/Products/Release/Pix Reader.app' 'build/macos/Build/Products/Release'
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            'build/macos/Build/Products/Release/Pix Reader ${{needs.tag.outputs.version}}.dmg'
  build-android:
    needs: [tag]
    if: needs.tag.outputs.version != ''
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build
        run: flutter build apk --release && mv build/app/outputs/flutter-apk/app-release.apk 'build/app/outputs/flutter-apk/Pix Reader ${{needs.tag.outputs.version}}.apk'
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: |
            'build/app/outputs/flutter-apk/Pix Reader ${{needs.tag.outputs.version}}.apk'
